settings:
  # Минимальное количество поинтов за убийство
  min-reward: 5
  # Максимальное количество поинтов за убийство
  max-reward: 15

messages:
  # Префикс плагина. Можно использовать & цвета и &#rrggbb
  prefix: "&#FF4500[AresPoints] &7"

  # Сообщение, когда нет прав
  no-permission: "&cУ вас нет прав на использование этой команды."

  # Сообщение при добавлении игрока в список (/ap setplayer)
  player-added: "&aИгрок &#FFFF00%player% &aтеперь получает поинты за убийства."

  # Сообщение при удалении игрока из списка (/ap remplayer)
  player-removed: "&cИгрок &#FFFF00%player% &cбольше не получает поинты."

  # Если игрок не был в списке при попытке удаления
  player-not-in-list: "&cЭтого игрока нет в списке активных."

  # Сообщение о перезагрузке конфига
  reload: "&aКонфигурация успешно перезагружена."

  # Сообщение с использованием команд
  usage: "&cИспользование: /arespoints <setplayer|remplayer|reload> <ник>"

  # Сообщение убийце при получении награды
  # %amount% - сумма поинтов, %victim% - ник убитого
  reward-received: "&aВы убили &e%victim% &aи получили &#00FF00+%amount% &aпоинтов!"